const P5_PROJECTS = [
  {
    id: 'hoamat-fashion-film',
    title: 'HOA MẮT – FASHION FILM',
    en: 'ILLUSION – FASHION FILM',
    year: '2026',
    role: 'Assistant Director',
    role_vi: 'Trợ lí đạo diễn',
    desc: 'Fashion Film nằm trong bộ sưu tập thời trang Hoa Mắt của Nguyễn Thị Phương Uyên, đồ án tốt nghiệp ngành Thiết kế thời trang trường Đại học Hoa Sen.',
    desc_vi: 'Fashion Film nằm trong bộ sưu tập thời trang Hoa Mắt của Nguyễn Thị Phương Uyên, đồ án tốt nghiệp ngành Thiết kế thời trang trường Đại học Hoa Sen.',
    about: [
      'Fashion Film nằm trong bộ sưu tập thời trang Hoa Mắt của Nguyễn Thị Phương Uyên, đồ án tốt nghiệp ngành Thiết kế thời trang trường Đại học Hoa Sen.',
    ],
    about_en: [
      'A Fashion Film for the Hoa Mắt fashion collection by Nguyễn Thị Phương Uyên, a graduation project from the Fashion Design program at Hoa Sen University.',
    ],
    credits: [
      { label: 'Executive Producer', label_vi: 'Giám đốc điều hành', value: 'Tân Taiyo' },
      { label: 'Creative & Directed by', label_vi: 'Sáng tạo & Đạo diễn', value: 'Aki Lê' },
      { label: 'Assistant Director', label_vi: 'Trợ lí đạo diễn', value: 'Quốc Hưng' },
      { label: 'Director of Photography & Camera Operator', label_vi: 'Quay phim & Camera Operator', value: 'Anh Duc' },
      { label: 'Focus Puller', label_vi: 'Chỉnh nét', value: 'Zu Nguyen' },
      { label: 'Makeup & Hairstylist', label_vi: 'Hóa trang & Tóc', value: 'Thảo Mochi' },
      { label: 'Makeup Assistant', label_vi: 'Trợ lý hóa trang', value: 'Châu Phát, Nguyễn Hậu' },
      { label: 'Stylist', label_vi: 'Phục trang', value: 'Lu, Hoàng Thyy, Huỳnh Thanh Danh, Khoa Bùi, Nguyễn Linh Chi' },
      { label: 'Set Designer & Props', label_vi: 'Thiết kế bối cảnh & Đạo cụ', value: 'Joe Huynh' },
      { label: 'Art Assistant', label_vi: 'Trợ lý mỹ thuật', value: 'Rin Le, Nguyễn Hoàng Hải' },
      { label: 'DIT & Offline Editor', label_vi: 'Quản lý dữ liệu & Dựng phim (Offline)', value: 'Phạm Toni' },
      { label: 'Rental Equipment', label_vi: 'Thiết bị', value: 'Cao Aly Team' },
      { label: 'Assistant Camera', label_vi: 'Trợ lý camera', value: 'Ngô Đặng Hoàng Nam, An Tran' },
      { label: 'Gaffer', label_vi: 'Gaffer', value: 'Quang Khangg' },
      { label: 'Lighting & Grip', label_vi: 'Ánh sáng & Grip', value: 'Cao Aly' },
      { label: 'Editor, VFX & Colorist', label_vi: 'Dựng phim, VFX & Chỉnh màu', value: 'Huy Hoàng Cao' },
      { label: 'Photographer', label_vi: 'Nhiếp ảnh', value: 'Phạm Đình Tấn' },
      { label: 'Photographer Assistant', label_vi: 'Trợ lý nhiếp ảnh', value: 'Nguyễn Quốc Việt, Nguyễn Quang Linh' },
      { label: 'Cast', label_vi: 'Diễn viên', value: 'Hoàng Yến, Kupbi Cat, Uyên Dolly, Ánh Tâm, Dicy' },
    ],
    stills: [],
    bts: [
      'assets/myproject/ad/HOAMAT/BTS/706766645_979982927985099_81399983172950205_n.jpg',
      'assets/myproject/ad/HOAMAT/BTS/707048332_1291922369311219_6995837072988478_n.jpg',
      'assets/myproject/ad/HOAMAT/BTS/708500902_1353951953268967_682713442482793_n.jpg',
      'assets/myproject/ad/HOAMAT/BTS/709525505_1315427126698698_2516492019700169478_n.jpg',
      'assets/myproject/ad/HOAMAT/BTS/710460809_1708268783927930_6034419701383928_n.jpg',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9001.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9008.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9009.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9016.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9067.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9069.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9074.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9090.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9110.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9125.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9128.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9130.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9132.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9144.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9159.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9164.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9191.JPG',
      'assets/myproject/ad/HOAMAT/BTS/DSCF9200.JPG',
    ],
    video: 'https://youtu.be/_q2RlreAwY0',
    video_ratio: '16/9',
    video_label: 'Link xem',
    video_label_en: 'Watch here',
    img: 'assets/myproject/ad/HOAMAT/Screenshot 2026-06-28 175846.png',
  },
  {
    id:'super-live-15-05-ha-linh',
    title:'SUPER LIVE 15.05 – HA LINH OFFICIAL',
    en:'SUPER LIVE 15.05 – HA LINH OFFICIAL',
    year:'2026',
    role:'2nd Assistant Director',
    role_vi:'Trợ lí đạo diễn 2',
    desc:'Funny viral clips promoting the Super Live session on May 15th on the Ha Linh Official channel.',
    desc_vi:'Các funny viral clip giới thiệu phiên live Super Live 15 tháng 05 trên kênh Ha Linh Official.',
    about:[
      'Các funny viral clip giới thiệu phiên live Super Live 15 tháng 05 trên kênh Ha Linh Official.',
    ],
    about_en:[
      'Funny viral clips promoting the Super Live session on May 15th on the Ha Linh Official channel.',
    ],
    credits:[
      { label:'Production House', label_vi:'Đơn vị sản xuất', value:'Fujima Pictures Production' },
      { label:'Executive Producer', label_vi:'Giám đốc điều hành', value:'Thông Hồ' },
      { label:'Producer', label_vi:'Sản xuất', value:'Thảo Nguyên Lê' },
      { label:'Project Manager', label_vi:'Quản lý dự án', value:'TR Thảo Uyên' },
      { label:'Director', label_vi:'Đạo diễn', value:'Puchin Nguyễn' },
      { label:'1st Assistant Director', label_vi:'Trợ lí đạo diễn 1', value:'Aki Lê' },
      { label:'2nd Assistant Director', label_vi:'Trợ lí đạo diễn 2', value:'Quốc Hưng' },
      { label:'Director of Photography', label_vi:'Quay phim', value:'Hoàng Trần' },
      { label:'Camera & Equipment', label_vi:'Camera & Thiết bị', value:'Tony Võ' },
      { label:'Props Team', label_vi:'Đạo cụ', value:'Tony Toàn' },
    ],
    stills:[],
    bts:[],
    video:'https://www.tiktok.com/@halinhofficial/video/7637392135636946184',
    video_ratio:'9/16',
    extras:[
      {
        url:'https://www.tiktok.com/@halinhofficial/video/7638548334541606151',
        ratio:'9/16',
      },
      {
        url:'https://www.tiktok.com/@halinhofficial/video/7638846285587500295',
        ratio:'9/16',
      },
    ],
    video_label:'Link xem',
    video_label_en:'Watch here',
    img:'assets/myproject/ad/Screenshot 2026-06-27 110515.png',
  },
  {
    id:'super-live-06-06-ha-linh',
    title:'SUPER LIVE 06.06 – HA LINH OFFICIAL',
    en:'SUPER LIVE 06.06 – HA LINH OFFICIAL',
    year:'2026',
    role:'2nd Assistant Director',
    role_vi:'Trợ lí đạo diễn 2',
    desc:'Funny viral clips promoting the Super Live session on June 6th on the Ha Linh Official channel.',
    desc_vi:'Các funny viral clip giới thiệu phiên live Super Live 06 tháng 06 trên kênh Ha Linh Official.',
    about:[
      'Các funny viral clip giới thiệu phiên live Super Live 06 tháng 06 trên kênh Ha Linh Official.',
    ],
    about_en:[
      'Funny viral clips promoting the Super Live session on June 6th on the Ha Linh Official channel.',
    ],
    credits:[
      { label:'Production House', label_vi:'Đơn vị sản xuất', value:'Fujima Pictures Production' },
      { label:'Executive Producer', label_vi:'Giám đốc điều hành', value:'Thông Hồ' },
      { label:'Producer', label_vi:'Sản xuất', value:'Thảo Nguyên Lê' },
      { label:'Project Manager', label_vi:'Quản lý dự án', value:'TR Thảo Uyên' },
      { label:'Director', label_vi:'Đạo diễn', value:'Cao Phi' },
      { label:'1st Assistant Director', label_vi:'Trợ lí đạo diễn 1', value:'Aki Lê' },
      { label:'2nd Assistant Director', label_vi:'Trợ lí đạo diễn 2', value:'Quốc Hưng' },
      { label:'Director of Photography', label_vi:'Quay phim', value:'Pha Nguyễn' },
      { label:'Camera & Equipment', label_vi:'Camera & Thiết bị', value:'Tony Võ' },
      { label:'Props Team', label_vi:'Đạo cụ', value:'Tony Toàn' },
    ],
    stills:[],
    bts:[],
    video:'https://www.tiktok.com/@halinhofficial/video/7645994745797332231',
    video_ratio:'9/16',
    extras:[
      {
        url:'https://www.tiktok.com/@halinhofficial/video/7647004518307187976',
        ratio:'9/16',
      },
    ],
    video_label:'Link xem',
    video_label_en:'Watch here',
    img:'assets/myproject/ad/Screenshot 2026-06-27 111012.png',
  },
  {
    id:'dieu-vien-khong-khong-hay',
    title:'ĐIỆP VIÊN KHÔNG KHÔNG HAY – PHIM NGẮN',
    en:'THE BASEMENT – SHORT FILM',
    year:'2026',
    role:'Assistant Director',
    role_vi:'Trợ lí đạo diễn',
    desc:'A short film by students of the Digital Film Production program at RMIT University.',
    desc_vi:'Phim ngắn của sinh viên ngành sản xuất phim kỹ thuật số trường Đại học RMIT.',
    about:[
      'Điệp Viên Không Không Hay là phim ngắn của sinh viên ngành sản xuất phim kỹ thuật số trường Đại học RMIT.',
    ],
    about_en:[
      'The Basement is a short film by students of the Digital Film Production program at RMIT University.',
    ],
    credits:[
      { label:'Director', label_vi:'Đạo diễn', value:'Vũ Hoàng' },
      { label:'1st Assistant Director', label_vi:'Trợ lí đạo diễn 1', value:'Quốc Hưng' },
      { label:'Producer', label_vi:'Sản xuất', value:'Kaituary' },
      { label:'Production Coordinator', label_vi:'Điều phối sản xuất', value:'Huyletran' },
      { label:'Production Assistant', label_vi:'Trợ lý sản xuất', value:'Thy, Buuu Nguyen, Nguyễn Gia Hân, Huỳnh Việt Bảo Phúc' },
      { label:'Script Supervisor', label_vi:'Giám sát kịch bản', value:'Kaituary' },
      { label:'Director of Photography', label_vi:'Quay phim', value:'Hoàng Quân' },
      { label:'Camera Operator', label_vi:'Camera Operator', value:'A Tới' },
      { label:'Camera Assistant', label_vi:'Trợ lý camera', value:'Pháp Trương, Dương Nguyễn' },
      { label:'Focus Puller', label_vi:'Chỉnh nét', value:'Dương Nguyễn (ItsZu)' },
      { label:'Gaffer', label_vi:'Gaffer', value:'Cao Aly' },
      { label:'Grip', label_vi:'Grip', value:'Trần Nam, Chung Chieh Wu, An Khang, Vũ Lưu Gia Huy, Lê Thanh Phong' },
      { label:'Sound Operator', label_vi:'Kỹ thuật âm thanh', value:'Nguyễn Tuấn Minh' },
      { label:'DIT', label_vi:'Quản lý dữ liệu', value:'Phan Hiền' },
      { label:'Production Designer', label_vi:'Thiết kế mỹ thuật', value:'Huỳnh BMinh' },
      { label:'Art Assistant', label_vi:'Trợ lý mỹ thuật', value:'Khanh Linh Bui, Mai Đinh, San San Dinh, Hoàng Hải' },
      { label:'Makeup Artist', label_vi:'Hóa trang', value:'Huỳnh BMinh' },
      { label:'Stylist', label_vi:'Phục trang', value:'Khánh Lin' },
      { label:'Editor', label_vi:'Dựng phim', value:'A Tới' },
      { label:'Colorist', label_vi:'Chỉnh màu', value:'Vũ Hoàng' },
      { label:'Sound Designer', label_vi:'Thiết kế âm thanh', value:'Nguyễn Tuấn Minh' },
      { label:'Post Producer', label_vi:'Hậu kỳ sản xuất', value:'Nguyễn Tuấn Minh' },
      { label:'BTS Photographer', label_vi:'Nhiếp ảnh hậu trường', value:'Nguyễn My, Hien Phan Cookies' },
      { label:'BTS Videographer', label_vi:'Quay hậu trường', value:'An Lý' },
      { label:'Featuring', label_vi:'Diễn viên', value:'Lê Anh Tuấn, Nguyễn Cao Đức Trí' },
    ],
    stills:[
      'assets/myproject/ad/basement%20still/686086918_1946055949605705_4162850247714430313_n.jpg',
      'assets/myproject/ad/basement%20still/686217324_1946056066272360_2143021523402775754_n.jpg',
      'assets/myproject/ad/basement%20still/686277030_1946055806272386_7576740043172495089_n.jpg',
      'assets/myproject/ad/basement%20still/686335474_1946056116272355_7547292840229406791_n.jpg',
      'assets/myproject/ad/basement%20still/686899739_1946055929605707_4537302003886607320_n.jpg',
      'assets/myproject/ad/basement%20still/686960184_1946056099605690_2548582344180028003_n.jpg',
      'assets/myproject/ad/basement%20still/686964449_1946055952939038_760119651991364595_n.jpg',
      'assets/myproject/ad/basement%20still/687306332_1946055816272385_1978068944892049951_n.jpg',
      'assets/myproject/ad/basement%20still/687332430_1946055819605718_4524128807550026168_n.jpg',
    ],
    bts:[
      'assets/myproject/ad/basement%20bts/DSC00001-2.jpg',
      'assets/myproject/ad/basement%20bts/DSC00001.jpg',
      'assets/myproject/ad/basement%20bts/DSC00002.jpg',
      'assets/myproject/ad/basement%20bts/DSC00014.jpg',
      'assets/myproject/ad/basement%20bts/DSC00015.jpg',
      'assets/myproject/ad/basement%20bts/DSC00018.jpg',
      'assets/myproject/ad/basement%20bts/DSC00020.jpg',
      'assets/myproject/ad/basement%20bts/DSC00037.jpg',
      'assets/myproject/ad/basement%20bts/DSC00122.jpg',
      'assets/myproject/ad/basement%20bts/DSC00150.jpg',
      'assets/myproject/ad/basement%20bts/DSC00197.jpg',
      'assets/myproject/ad/basement%20bts/DSC00226.jpg',
      'assets/myproject/ad/basement%20bts/DSC00231.jpg',
      'assets/myproject/ad/basement%20bts/DSC00235.jpg',
      'assets/myproject/ad/basement%20bts/DSC00236.jpg',
      'assets/myproject/ad/basement%20bts/DSC00237.jpg',
      'assets/myproject/ad/basement%20bts/DSC00240.jpg',
      'assets/myproject/ad/basement%20bts/DSC00241-2.jpg',
      'assets/myproject/ad/basement%20bts/DSC00241.jpg',
      'assets/myproject/ad/basement%20bts/DSC00242.jpg',
      'assets/myproject/ad/basement%20bts/DSC00243.jpg',
      'assets/myproject/ad/basement%20bts/DSC00246.jpg',
      'assets/myproject/ad/basement%20bts/DSC00253.jpg',
      'assets/myproject/ad/basement%20bts/DSC00306.jpg',
      'assets/myproject/ad/basement%20bts/DSC00308.jpg',
      'assets/myproject/ad/basement%20bts/DSC00309.jpg',
      'assets/myproject/ad/basement%20bts/DSC00312.jpg',
      'assets/myproject/ad/basement%20bts/DSC00313.jpg',
      'assets/myproject/ad/basement%20bts/DSC00322-2.jpg',
      'assets/myproject/ad/basement%20bts/DSC00322.jpg',
      'assets/myproject/ad/basement%20bts/DSC00324.jpg',
      'assets/myproject/ad/basement%20bts/DSC00327.jpg',
      'assets/myproject/ad/basement%20bts/DSC00333.jpg',
      'assets/myproject/ad/basement%20bts/DSC00336.jpg',
      'assets/myproject/ad/basement%20bts/DSC00347.jpg',
      'assets/myproject/ad/basement%20bts/DSC00365.jpg',
      'assets/myproject/ad/basement%20bts/DSC00374.jpg',
      'assets/myproject/ad/basement%20bts/DSC00375.jpg',
      'assets/myproject/ad/basement%20bts/DSC00380.jpg',
      'assets/myproject/ad/basement%20bts/DSC00382.jpg',
      'assets/myproject/ad/basement%20bts/DSC00386.jpg',
      'assets/myproject/ad/basement%20bts/DSC00389.jpg',
      'assets/myproject/ad/basement%20bts/DSC00396.jpg',
      'assets/myproject/ad/basement%20bts/DSC00402.jpg',
      'assets/myproject/ad/basement%20bts/DSC00404.jpg',
      'assets/myproject/ad/basement%20bts/DSC00407.jpg',
      'assets/myproject/ad/basement%20bts/DSC00416.jpg',
      'assets/myproject/ad/basement%20bts/DSC00419.jpg',
      'assets/myproject/ad/basement%20bts/DSC00420.jpg',
      'assets/myproject/ad/basement%20bts/DSC00427.jpg',
      'assets/myproject/ad/basement%20bts/DSC00435.jpg',
      'assets/myproject/ad/basement%20bts/DSC00453.jpg',
      'assets/myproject/ad/basement%20bts/DSC00463.jpg',
      'assets/myproject/ad/basement%20bts/DSC09610.jpg',
      'assets/myproject/ad/basement%20bts/DSC09611.jpg',
      'assets/myproject/ad/basement%20bts/DSC09613.jpg',
      'assets/myproject/ad/basement%20bts/DSC09616.jpg',
      'assets/myproject/ad/basement%20bts/DSC09618.jpg',
      'assets/myproject/ad/basement%20bts/DSC09623.jpg',
      'assets/myproject/ad/basement%20bts/DSC09625.jpg',
      'assets/myproject/ad/basement%20bts/DSC09636.jpg',
      'assets/myproject/ad/basement%20bts/DSC09639.jpg',
      'assets/myproject/ad/basement%20bts/DSC09643.jpg',
      'assets/myproject/ad/basement%20bts/DSC09648.jpg',
      'assets/myproject/ad/basement%20bts/DSC09652.jpg',
      'assets/myproject/ad/basement%20bts/DSC09653.jpg',
      'assets/myproject/ad/basement%20bts/DSC09658.jpg',
      'assets/myproject/ad/basement%20bts/DSC09662.jpg',
      'assets/myproject/ad/basement%20bts/DSC09664.jpg',
      'assets/myproject/ad/basement%20bts/DSC09665.jpg',
      'assets/myproject/ad/basement%20bts/DSC09667.jpg',
      'assets/myproject/ad/basement%20bts/DSC09681.jpg',
      'assets/myproject/ad/basement%20bts/DSC09689.jpg',
      'assets/myproject/ad/basement%20bts/DSC09690.jpg',
      'assets/myproject/ad/basement%20bts/DSC09691.jpg',
      'assets/myproject/ad/basement%20bts/DSC09693.jpg',
      'assets/myproject/ad/basement%20bts/DSC09699.jpg',
      'assets/myproject/ad/basement%20bts/DSC09702.jpg',
      'assets/myproject/ad/basement%20bts/DSC09704.jpg',
      'assets/myproject/ad/basement%20bts/DSC09706.jpg',
      'assets/myproject/ad/basement%20bts/DSC09708.jpg',
      'assets/myproject/ad/basement%20bts/DSC09709.jpg',
      'assets/myproject/ad/basement%20bts/DSC09710.jpg',
      'assets/myproject/ad/basement%20bts/DSC09713.jpg',
      'assets/myproject/ad/basement%20bts/DSC09714.jpg',
      'assets/myproject/ad/basement%20bts/DSC09716.jpg',
      'assets/myproject/ad/basement%20bts/DSC09717.jpg',
      'assets/myproject/ad/basement%20bts/DSC09719.jpg',
      'assets/myproject/ad/basement%20bts/DSC09720.jpg',
      'assets/myproject/ad/basement%20bts/DSC09726.jpg',
      'assets/myproject/ad/basement%20bts/DSC09735.jpg',
      'assets/myproject/ad/basement%20bts/DSC09737.jpg',
      'assets/myproject/ad/basement%20bts/DSC09743.jpg',
      'assets/myproject/ad/basement%20bts/DSC09751.jpg',
      'assets/myproject/ad/basement%20bts/DSC09754.jpg',
      'assets/myproject/ad/basement%20bts/DSC09755.jpg',
      'assets/myproject/ad/basement%20bts/DSC09756.jpg',
      'assets/myproject/ad/basement%20bts/DSC09758.jpg',
      'assets/myproject/ad/basement%20bts/DSC09761.jpg',
      'assets/myproject/ad/basement%20bts/DSC09766.jpg',
      'assets/myproject/ad/basement%20bts/DSC09768.jpg',
      'assets/myproject/ad/basement%20bts/DSC09770.jpg',
      'assets/myproject/ad/basement%20bts/DSC09771.jpg',
      'assets/myproject/ad/basement%20bts/DSC09773.jpg',
      'assets/myproject/ad/basement%20bts/DSC09784.jpg',
      'assets/myproject/ad/basement%20bts/DSC09800.jpg',
      'assets/myproject/ad/basement%20bts/DSC09801.jpg',
      'assets/myproject/ad/basement%20bts/DSC09802.jpg',
      'assets/myproject/ad/basement%20bts/DSC09803.jpg',
      'assets/myproject/ad/basement%20bts/DSC09808.jpg',
      'assets/myproject/ad/basement%20bts/DSC09814.jpg',
      'assets/myproject/ad/basement%20bts/DSC09826.jpg',
      'assets/myproject/ad/basement%20bts/DSC09829.jpg',
      'assets/myproject/ad/basement%20bts/DSC09831.jpg',
      'assets/myproject/ad/basement%20bts/DSC09835.jpg',
      'assets/myproject/ad/basement%20bts/DSC09837.jpg',
      'assets/myproject/ad/basement%20bts/DSC09838.jpg',
      'assets/myproject/ad/basement%20bts/DSC09852.jpg',
      'assets/myproject/ad/basement%20bts/DSC09859.jpg',
      'assets/myproject/ad/basement%20bts/DSC09868.jpg',
      'assets/myproject/ad/basement%20bts/DSC09869.jpg',
      'assets/myproject/ad/basement%20bts/DSC09875.jpg',
      'assets/myproject/ad/basement%20bts/DSC09885.jpg',
      'assets/myproject/ad/basement%20bts/DSC09888.jpg',
      'assets/myproject/ad/basement%20bts/DSC09899.jpg',
      'assets/myproject/ad/basement%20bts/DSC09906.jpg',
      'assets/myproject/ad/basement%20bts/DSC09914.jpg',
      'assets/myproject/ad/basement%20bts/DSC09916.jpg',
      'assets/myproject/ad/basement%20bts/DSC09923.jpg',
      'assets/myproject/ad/basement%20bts/DSC09926.jpg',
      'assets/myproject/ad/basement%20bts/DSC09930.jpg',
      'assets/myproject/ad/basement%20bts/DSC09936.jpg',
      'assets/myproject/ad/basement%20bts/DSC09950.jpg',
      'assets/myproject/ad/basement%20bts/DSC09952.jpg',
      'assets/myproject/ad/basement%20bts/DSC09965.jpg',
      'assets/myproject/ad/basement%20bts/DSC09972.jpg',
      'assets/myproject/ad/basement%20bts/DSC09984.jpg',
      'assets/myproject/ad/basement%20bts/DSC09990.jpg',
      'assets/myproject/ad/basement%20bts/DSC09991.jpg',
      'assets/myproject/ad/basement%20bts/DSC09996.jpg',
      'assets/myproject/ad/basement%20bts/DSC09997.jpg',
      'assets/myproject/ad/basement%20bts/DSC09998.jpg',
      'assets/myproject/ad/basement%20bts/DSC09999.jpg',
    ],
    video:'https://www.youtube.com/watch?v=fGTSLTKOX0k',
    video_label:'Link xem',
    video_label_en:'Watch here',
    img:'assets/myproject/ad/basement%20still/686086918_1946055949605705_4162850247714430313_n.jpg',
  },
  {
    id:'co-biec-hoa-vang-narcis',
    title:'CỎ BIẾC HOÁ VÀNG | NARCIS & KAZANALAM – MUSIC VIDEO',
    en:'CỎ BIẾC HOÁ VÀNG | NARCIS & KAZANALAM – MUSIC VIDEO',
    year:'2026',
    role:'1st Assistant Director',
    role_vi:'Trợ lí đạo diễn 1',
    desc:'A traditional Cải Lương music video inspired by Tiếng Trống Mê Linh, produced by Keep Rollin.',
    desc_vi:'MV truyền thống về Cải Lương, lấy cảm hứng từ Tiếng Trống Mê Linh, sản xuất bởi Keep Rollin.',
    about:[
      'Cỏ Biếc Hoá Vàng là MV truyền thống về Cải Lương, lấy cảm hứng từ Tiếng Trống Mê Linh, sản xuất bởi Keep Rollin.',
    ],
    about_en:[
      'Cỏ Biếc Hoá Vàng is a traditional Cải Lương music video inspired by Tiếng Trống Mê Linh, produced by Keep Rollin.',
    ],
    credits:[
      { label:'Director & Screenwriter', label_vi:'Đạo diễn & Biên kịch', value:'Minh Hạ' },
      { label:'1st Assistant Director', label_vi:'Trợ lí đạo diễn 1', value:'Quốc Hưng, Đặng Thành Tâm' },
      { label:'2nd Assistant Director', label_vi:'Trợ lí đạo diễn 2', value:'Reanisntreal, Huỳnh Nhật Nguyên' },
      { label:'Project Manager', label_vi:'Quản lý dự án', value:'Tieu Chi' },
      { label:'Producer', label_vi:'Sản xuất', value:'Ngọc Trinh, Tuyết Nhi' },
      { label:'Line Producer', label_vi:'Trưởng sản xuất', value:'Tuyết Nhi, Mai Anh' },
      { label:'Director of Photography', label_vi:'Quay phim', value:'Nguyễn Thành Hiếu (Puchin)' },
      { label:'Camera Operator', label_vi:'Camera Operator', value:'Nguyễn Thành Hiếu (Puchin), Hoàng Trần, Khoa Nguyễn' },
      { label:'Art Director', label_vi:'Giám đốc nghệ thuật', value:'Phương Vy' },
      { label:'Art Assistant', label_vi:'Trợ lý mỹ thuật', value:'Hạ Vi' },
      { label:'Cải Lương Make-up', label_vi:'Hóa trang Cải Lương', value:'Cô Ngọc Nga' },
      { label:'Hairstylist', label_vi:'Tóc', value:'Cô Ngọc Nga, Nam Nguyễn' },
      { label:'Wardrobe', label_vi:'Phục trang', value:'Kim Ngân, Thuỳ Trinh' },
      { label:'Stage Choreographer', label_vi:'Biên đạo sân khấu', value:'Sơn Giang' },
      { label:'Editor & Sound Editing', label_vi:'Dựng phim & Chỉnh âm', value:'Dinh_goc (VEIN)' },
      { label:'VFX & Colorist', label_vi:'VFX & Chỉnh màu', value:'Nguyên Phan (VEIN)' },
      { label:'Starring', label_vi:'Diễn viên', value:'Tú Quyên, Hồng Quyên, Thủy Tiên (narcis), Đổng Tường, Hạnh Phúc' },
    ],
    stills:[],
    bts:[
      'assets/myproject/ad/cbhv/1b9e304e-2676-45ff-beb5-97a90b832b93.jpg',
      'assets/myproject/ad/cbhv/580c7db0-3909-411d-84ae-bac2f5ff0f77.jpg',
      'assets/myproject/ad/cbhv/88f532b2-7ede-4cda-9b58-69756fb48aa4.jpg',
      'assets/myproject/ad/cbhv/9595b426-d1d9-44cb-99c4-9c352516f44d.jpg',
      'assets/myproject/ad/cbhv/982fa226-e549-4cfd-8d5f-ee574a5aba78.jpg',
      'assets/myproject/ad/cbhv/ae2b5f87-ed73-4f9b-b4ce-a770bc0437bd.jpg',
      'assets/myproject/ad/cbhv/bcbfeb74-3081-4684-8aae-234f66d7d158.jpg',
      'assets/myproject/ad/cbhv/c824eb2f-0e66-4a66-8ca7-5d61d317a554.jpg',
      'assets/myproject/ad/cbhv/cbba0b09-5c48-489e-8091-25edcf75ad0b.jpg',
      'assets/myproject/ad/cbhv/DSC07338.JPG',
      'assets/myproject/ad/cbhv/DSC07419.JPG',
      'assets/myproject/ad/cbhv/DSC07423.JPG',
      'assets/myproject/ad/cbhv/DSC07450.JPG',
      'assets/myproject/ad/cbhv/DSC07528.JPG',
      'assets/myproject/ad/cbhv/DSC07574.JPG',
      'assets/myproject/ad/cbhv/DSC07579.JPG',
      'assets/myproject/ad/cbhv/DSC07596.JPG',
      'assets/myproject/ad/cbhv/DSC07600.JPG',
      'assets/myproject/ad/cbhv/DSC07612.JPG',
      'assets/myproject/ad/cbhv/DSC07722.JPG',
      'assets/myproject/ad/cbhv/DSC07770.JPG',
      'assets/myproject/ad/cbhv/DSC07798.JPG',
      'assets/myproject/ad/cbhv/DSC08000.JPG',
      'assets/myproject/ad/cbhv/DSC08053.ARW',
      'assets/myproject/ad/cbhv/DSC08121.JPG',
      'assets/myproject/ad/cbhv/DSCF3356.JPG',
      'assets/myproject/ad/cbhv/DSCF3374.JPG',
      'assets/myproject/ad/cbhv/DSCF3471.JPG',
      'assets/myproject/ad/cbhv/DSCF3497.JPG',
      'assets/myproject/ad/cbhv/DSCF3552.JPG',
      'assets/myproject/ad/cbhv/DSCF3650.JPG',
      'assets/myproject/ad/cbhv/DSCF3946.JPG',
      'assets/myproject/ad/cbhv/DSCF4114.JPG',
      'assets/myproject/ad/cbhv/DSCF4178.JPG',
      'assets/myproject/ad/cbhv/DSCF4340.JPG',
      'assets/myproject/ad/cbhv/DSCF4417.JPG',
      'assets/myproject/ad/cbhv/e93396cb-5510-43a3-9257-c408e145f559.jpg',
    ],
    video:'https://www.youtube.com/watch?v=1Xg5xW5IDo4',
    video_label:'Link xem',
    video_label_en:'Watch here',
    img:'assets/myproject/ad/cbhv grid.jpg',
  },
  {
    id:'cloudtopia-maybelline',
    video:'https://www.facebook.com/reel/1689877472012143',
    video_label:'Link xem',
    video_label_en:'Watch here',
    title:'SON MÂY ĐA NĂNG CLOUDTOPIA – MAYBELLINE NEW YORK',
    en:'CLOUDTOPIA MULTI-USE LIP CLOUD – MAYBELLINE NEW YORK',
    year:'2026',
    role:'Assistant Director',
    role_vi:'Trợ lí đạo diễn',
    desc:'A TVC introducing the Cloudtopia Multi-Use Lip Cloud product by Maybelline New York, in collaboration with KOL Linh Ka.',
    desc_vi:'TVC giới thiệu sản phẩm son mây đa năng Cloudtopia của Maybelline New York, hợp tác cùng KOL Linh Ka.',
    about:[
      'TVC giới thiệu sản phẩm son mây đa năng Cloudtopia của Maybelline New York, hợp tác cùng KOL Linh Ka.',
    ],
    about_en:[
      'A TVC introducing the Cloudtopia Multi-Use Lip Cloud product by Maybelline New York, in collaboration with KOL Linh Ka.',
    ],
    credits:[
      { label:'Client', label_vi:'Khách hàng', value:'Maybelline AGC' },
      { label:'Production Company', label_vi:'Công ty sản xuất', value:'Genie Studio' },
      { label:'Art Director', label_vi:'Giám đốc nghệ thuật', value:'Ly Cao, Le Ho An' },
      { label:'Account', label_vi:'Kế toán', value:'Genie Huynh, Thuy Linh' },
      { label:'Director', label_vi:'Đạo diễn', value:'Durian Phạm' },
      { label:'Assistant Director', label_vi:'Trợ lí đạo diễn', value:'Nguyễn Vũ Quốc Hưng' },
      { label:'Camera Operator', label_vi:'Camera Operator', value:'Thien Nhat' },
      { label:'Gaffer', label_vi:'Gaffer', value:'Minh Ngoc' },
      { label:'Producer', label_vi:'Sản xuất', value:'Quynh Mai' },
      { label:'Production Assistant', label_vi:'Trợ lý sản xuất', value:'Tuong Vy, Gia Nghi' },
      { label:'Offline Editor', label_vi:'Dựng phim (Offline)', value:'Hau Nguyen Duy' },
      { label:'Online Editor', label_vi:'Dựng phim (Online)', value:'Do Duong Hoang Minh, Anh Vu Nguyen' },
      { label:'Starring', label_vi:'Diễn viên', value:'Linh Ka' },
    ],
    stills:[],
    bts:[],
    img:'assets/myproject/ad/mlb.png',
  },
  {
    id:'hoa-no-tren-tan-thuoc',
    video:'https://www.facebook.com/watch/?v=3537786149858442',
    title:'HOA NỞ TRÊN TÀN THUỐC',
    en:'FLOWERS BLOOM ON CIGARETTE ASHES',
    year:'2024',
    role:'Assistant Director',
    role_vi:'Trợ lí đạo diễn',
    desc:'A student short film from Van Lang University. Screened at Lift Off Session 2026 Volume 1, FABA Film Festival, and selected for Węgiel Film Festival.',
    desc_vi:'Phim ngắn sinh viên của trường Đại học Văn Lang. Phim được trình chiếu tại Lift Off Session 2026 Volume 1, FABA Film Festival và được chọn tham gia Węgiel Film Festival.',
    about:[
      'Hoa Nở Trên Tàn Thuốc là phim ngắn sinh viên của trường Đại học Văn Lang, được trình chiếu tại Lift Off Session 2026 Volume 1, FABA Film Festival và được chọn tham gia Węgiel Film Festival.',
    ],
    about_en:[
      'Flowers Bloom on Cigarette Ashes is a student short film from Van Lang University, screened at Lift Off Session 2026 Volume 1, FABA Film Festival, and selected for Węgiel Film Festival.',
    ],
    credits:[
      { label:'Director', label_vi:'Đạo diễn', value:'Huỳnh Việt Bảo Phúc' },
      { label:'1st Assistant Director', label_vi:'Trợ lí đạo diễn 1', value:'Quốc Hưng' },
      { label:'Producer', label_vi:'Sản xuất', value:'Phan Quốc Anh, Phan Thiện Anh, Vũ Đức Hùng, Huỳnh Việt Bảo Phúc' },
      { label:'Director of Photography', label_vi:'Quay phim', value:'Hà Tất Thành' },
      { label:'Gaffer', label_vi:'Gaffer', value:'Trần Thành Công' },
      { label:'Art Director', label_vi:'Giám đốc nghệ thuật', value:'Phạm Kim Mỹ' },
      { label:'Starring', label_vi:'Diễn viên', value:'Vũ Đức Hùng, Mai Ngọc Nhi, Lê Nguyễn Duy, …' },
    ],
    stills:[
      'assets/myproject/ad/hoa nở trên tàn thuốc/1.jpg',
      'assets/myproject/ad/hoa nở trên tàn thuốc/2.jpg',
      'assets/myproject/ad/hoa nở trên tàn thuốc/3.jpg',
      'assets/myproject/ad/hoa nở trên tàn thuốc/4.jpg',
      'assets/myproject/ad/hoa nở trên tàn thuốc/5.jpg',
      'assets/myproject/ad/hoa nở trên tàn thuốc/6.jpg',
      'assets/myproject/ad/hoa nở trên tàn thuốc/7.png',
    ],
    bts:[],
    img:'assets/myproject/ad/hoa nở trên tàn thuốc/1.jpg',
  },
  {
    id:'hoang-hon-cua-chung-ta',
    video:'https://www.youtube.com/watch?v=S0OC8nRRutc&t=1s',
    title:'HOÀNG HÔN CỦA CHÚNG TA',
    en:'OUR SUNSET',
    year:'2024',
    role:'Assistant Director',
    role_vi:'Trợ lí đạo diễn',
    desc:'A two-episode short film, part of the Hơi Vui Vui TV series produced by TKM Production and Vibe Bros Team.',
    desc_vi:'Phim ngắn gồm hai tập, nằm trong series Hơi Vui Vui TV được sản xuất bởi TKM Production và Vibe Bros Team.',
    about:[
      'Hoàng Hôn Của Chúng Ta là phim ngắn gồm hai tập, nằm trong series Hơi Vui Vui TV được sản xuất bởi TKM Production và Vibe Bros Team.',
    ],
    about_en:[
      'Our Sunset is a two-episode short film, part of the Hơi Vui Vui TV series produced by TKM Production and Vibe Bros Team.',
    ],
    extras:[
      {
        label:'Tập 2',
        label_en:'Episode 2',
        url:'https://www.youtube.com/watch?v=C_oEzQmP55Q&t=335s',
      },
    ],
    credits:[
      { label:'Executive Producer', label_vi:'Giám đốc điều hành', value:'Quốc Bảo TKM' },
      { label:'Project Manager', label_vi:'Quản lý dự án', value:'Dương Rii' },
      { label:'Production Units', label_vi:'Đơn vị sản xuất', value:'TKM Production, Vibe Bros Team' },
      { label:'Director', label_vi:'Đạo diễn', value:'Phúc Vũ' },
      { label:'1st Assistant Director', label_vi:'Trợ lí đạo diễn 1', value:'Quốc Hưng' },
      { label:'Director of Photography', label_vi:'Quay phim', value:'Việt Lê, Hồng Sơn Trần' },
      { label:'Starring', label_vi:'Diễn viên', value:'Thanh Thúy, Dương Mạnh, Hải Mi, Senpai Thành, Yên Dương, …' },
    ],
    stills:[
      'assets/myproject/ad/hhcct/maxresdefault.jpg',
    ],
    bts:[],
    img:'assets/myproject/ad/hhcct/maxresdefault.jpg',
  },
  {
    id:'shipaholic',
    video:'https://www.youtube.com/watch?v=7v4_zNXeUTc',
    title:'SHIPAHOLIC',
    en:'SHIPAHOLIC',
    year:'2025',
    role:'Assistant Director, Editor',
    role_vi:'Trợ lí đạo diễn, Dựng phim',
    desc:'A creative class project by RMIT students to promote the board game "Shipaholic".',
    desc_vi:'TVC là dự án học thuật của sinh viên trường RMIT, quảng bá cho trò chơi board game "Shipaholic".',
    about:[
      'Shipaholic là TVC thuộc dự án học thuật của sinh viên trường RMIT, được thực hiện để quảng bá cho trò chơi board game "Shipaholic".',
    ],
    about_en:[
      'Shipaholic is a creative class project by RMIT students, produced to promote the board game "Shipaholic".',
    ],
    credits:[],
    stills:[],
    bts:[
      'assets/myproject/ad/shipaholic/still/image (1).png',
      'assets/myproject/ad/shipaholic/still/image (2).png',
      'assets/myproject/ad/shipaholic/still/image.png',
      'assets/myproject/ad/shipaholic/still/IMG_0512.JPG.jpg',
      'assets/myproject/ad/shipaholic/still/IMG_0570.JPG.jpg',
      'assets/myproject/ad/shipaholic/still/IMG_0585.JPG.jpg',
      'assets/myproject/ad/shipaholic/still/IMG_3455.JPG.jpg',
      'assets/myproject/ad/shipaholic/still/IMG_3527.jpeg',
      'assets/myproject/ad/shipaholic/still/IMG_3539.jpeg',
    ],
    img:'assets/myproject/ad/shipaholic/Screenshot 2026-03-17 145902.png',
  },
  {
    id:'buoc-chay-khong-tieng-vo-tay',
    video:'https://www.facebook.com/reel/938797588544489',
    title:'BƯỚC CHẠY KHÔNG TIẾNG VỖ TAY',
    en:'THE SILENT RUN',
    year:'2025',
    role:'Assistant Director',
    role_vi:'Trợ lí đạo diễn',
    desc:'A pre-graduation short film by students of Van Lang University.',
    desc_vi:'Phim ngắn tiền tốt nghiệp của sinh viên trường Đại học Văn Lang.',
    about:[
      'Bước Chạy Không Tiếng Vỗ Tay là phim ngắn tiền tốt nghiệp của sinh viên trường Đại học Văn Lang.',
    ],
    about_en:[
      'The Silent Run is a pre-graduation short film by students of Van Lang University.',
    ],
    credits:[
      { label:'Assistant Director', label_vi:'Trợ lí đạo diễn', value:'Quốc Hưng' },
      { label:'Producer', label_vi:'Sản xuất', value:'Hà Nam Ngô, Minh Anh' },
      { label:'Line Producer', label_vi:'Trưởng sản xuất', value:'Lê Hoàng Thanh' },
      { label:'Production Assistant', label_vi:'Trợ lý sản xuất', value:'Hoàng Lan, Ngọc Mai, An Khang' },
      { label:'Director of Photography', label_vi:'Quay phim', value:'Trần Thanh Tùng' },
      { label:'Camera Operator', label_vi:'Camera Operator', value:'Hoàng Tú' },
      { label:'Art Director', label_vi:'Giám đốc nghệ thuật', value:'Nick Ng, Hoàng Hải' },
      { label:'Props Master', label_vi:'Đạo cụ', value:'Thanh Trúc' },
      { label:'Set Designer', label_vi:'Thiết kế bối cảnh', value:'Sơn Lê, Huỳnh Việt Bảo Phúc, Khánh Vũ' },
      { label:'Wardrobe Coordinator', label_vi:'Phục trang', value:'Trần Hoàng Minh Quân' },
      { label:'VFX Editor', label_vi:'Dựng & Kỹ xảo', value:'Huy Hoàng Cao' },
      { label:'Cast', label_vi:'Diễn viên', value:'Trần Long, Nguyễn Trực, Bé Trí Thịnh' },
    ],
    stills:[],
    bts:[
      'assets/myproject/ad/bcktvt/bts/z7066891627610_35f0395f536ffa064177ca357a6d127a.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066891661288_aaae3cad5dc01bae2c1d5dedcdadef56.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066891689106_626f4b93e7026597543519141fac3ae0.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066891710263_dbf54d04d0bdce98014d83fa9db9da8d.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066891739049_91654ef8476f571c12977e120c370aa4.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066891914653_d6d815cfd6d6f2b9f35e35bebba5cfbb.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066891916592_2585764008be0a219624906807e6d08f.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066891932690_73c36d72333a92ce636b69db3c04dc3c.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066891973562_5ef39587670b1d8f94cc92c49493fb09.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066891973820_3e54df07ba898ef5d34b1d6366fc0737.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066891984446_8364ae591228f5aa586ba4af6297247a.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066891990681_9e4deaae4b4862e26a64fd130c9300bd.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892006958_4aeb9d90a627f9fa40318b1ffd3a29a7.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892015363_5c32f9e6a16533bba9928e74f4a6473a.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892043797_c50a84048c787072de5b011e2f609e08.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892045906_9a7f9213856a576f927d68a65677156e.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892064232_4a2a94a6fdaad747384e24c3367bd2ae.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892072208_e15b99a7bb77c39b26ae03bc8f5905e5.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892086675_e8a4238dbf65fd00d1b7ffa90b6bdad3.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892088729_e497345d7efab162b08d7e9ac5252740.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892201596_50704fe4fd9bf16622fe46c521c89259.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892241004_6d0e0b1336fd9fe53f67e754221be09d.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892251292_17d9ce9834e0e30c89a95f3a6eb6871e.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892253328_3222292df46b41098c31ca63eb3dc291.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892304266_3e574581ca1c7c54eaa181c24faad4b1.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892337906_435b10b1af49c283430f859e61087acd.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892353655_78af8597f8eab2b39f91b653234082da.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892365610_ecf02fbd5666d7f90f14773e4982a93c.jpg',
      'assets/myproject/ad/bcktvt/bts/z7066892399472_647f08af81c364ad74a4fb6c1150aa49.jpg',
    ],
    img:'assets/myproject/ad/bcktvt/Still1.jpg',
  }
];

function renderP5() {
  const projects = (window._P5 || P5_PROJECTS)
    .map((proj, idx) => ({ proj, idx }))
    .sort((a, b) => {
      const yearA = Number.parseInt(a.proj.year, 10) || 0;
      const yearB = Number.parseInt(b.proj.year, 10) || 0;
      if (yearA !== yearB) return yearB - yearA;
      return a.idx - b.idx;
    })
    .map(item => item.proj);
  const grid = document.getElementById('p5-grid');
  grid.innerHTML = projects.map(proj => `
    <div class="p5-card" onclick="goToProjectPage('${proj.id}',5)">
      <div class="p5-card-img-wrap">
        ${proj.img
          ? `<img src="${proj.img}" alt="${proj.title}"/>
             <div class="p5-card-img-overlay"></div>`
          : `<div class="p5-card-img-placeholder">
               <svg width="48" height="48" viewBox="0 0 48 48" fill="none">
                 <rect x="4" y="10" width="40" height="28" rx="2" stroke="#ff1a1a" stroke-width=".8"/>
                 <circle cx="16" cy="20" r="4" stroke="#ff1a1a" stroke-width=".8"/>
                 <path d="M4 34 L16 22 L26 32 L34 24 L44 34" stroke="#ff1a1a" stroke-width=".8" fill="none"/>
               </svg>
             </div>`
        }
      </div>
      <div class="p5-card-body">
        <div class="p5-card-title">${currentLang === 'en' && proj.en ? proj.en : proj.title}</div>
        <div class="p5-card-meta">${proj.year} — ${currentLang === 'en' ? proj.role : (proj.role_vi || proj.role)}</div>
        <div class="p5-card-desc">${currentLang === 'en' ? proj.desc : (proj.desc_vi || proj.desc)}</div>
      </div>
    </div>`).join('');
}

function goToPage5() {
  if (currentPage === 5) return;
  if (window.hideFloatingWords) hideFloatingWords();
  if (window.stopHomeMusic) stopHomeMusic();
  if (window.resetAllPages) resetAllPages();
  currentPage = 5;
  if (window.pushRoute) pushRoute('/assistant-director');
  if (window.updateSideNav) updateSideNav(5);
  renderP5();
  document.getElementById('p1').classList.add('slide-out');
  document.getElementById('p5').classList.add('slide-in');
  document.getElementById('p5-scroll').scrollTop = 0;
  setTimeout(() => {
    document.getElementById('p5-header').classList.add('in');
    document.getElementById('p5-divider').classList.add('in');
  }, 120);
  setTimeout(() => {
    document.getElementById('p5-grid').classList.add('in');
  }, 340);
  const p2hint = document.getElementById('p2-hint');
  if (p2hint) p2hint.style.display = 'none';
  if (window.updateMenuState) updateMenuState();
}

function goToPage1FromP5() {
  if (currentPage !== 5) return;
  currentPage = 1;
  if (window.pushRoute) pushRoute('/');
  document.getElementById('p1').classList.remove('slide-out');
  document.getElementById('p5').classList.remove('slide-in');
  setTimeout(() => {
    document.getElementById('p5-header').classList.remove('in');
    document.getElementById('p5-divider').classList.remove('in');
    document.getElementById('p5-grid').classList.remove('in');
  }, 720);
  returnWords();
  if (window.updateMenuState) updateMenuState();
}

