/* ══ CONTENT ════════════════════════════════ */
const C = {
  en:{
    sub:'Freelance Filmmaker — Ho Chi Minh City', hint:'',
    nsub:'Freelance Filmmaker — Ho Chi Minh City',
    resFile:'assets/CV_ENG.pdf', resTxt:'Download Resume',
    lblAbout:'About Me', lblFilms:'Filmography & Awards',
    lblSw:'Software Proficiency', lblExp:'Expertise',
    about:[
      'I am Nguyễn Vũ Quốc Hưng, an emerging filmmaker and freelance Director, Producer, Assistant Director, and Editor, based in Ho Chi Minh City.',
      'I am on a journey to discover who I am in this vast world, with filmmaking as my chosen path toward that answer.',
      'As an emerging filmmaker, I actively seek opportunities across all film crew positions — combining my skills with an eagerness to learn, committed to excellence in whatever role I undertake.',
    ],
    quote:'"You only get back what you are prepared to put in." — Hirokazu Kore-eda',
    films:[
      {type:'Short Film',title:'Hạnh Phúc Của Ánh Dương',en:"Sunshine's Happiness",
       awards:['Best Short Film — "1 Minute to Shine 2023" (FPT University)']},
      {type:'Short Documentary',title:'Thêm Một "Dấu Phẩy"',en:'Add a "Comma"',
       awards:['Official screening — Lagi Short Film Night (Trigger Film Academy)',
               'Official selection — Xinê Xem Fest 2024 (Xinê House)',
               'Official selection — Filmmaker Lift-Off Sessions 2026, Vol. 1',
               'Audience Choice Winner — Filmmaker Lift-Off Sessions 2026, Vol. 1']},
      {type:'Short Film',title:'Lặng Lẽ Trôi Về',en:'The River Knows The Way Home',
       awards:['Official selection — Filmmaker Lift-Off Sessions 2026, Vol. 1',
               "Jury's Winner (Grand Prize) — Filmmaker Lift-Off Sessions 2026, Vol. 1",
               'Nominated — Filmmaker Lift-Off Season Awards 2026']},
      {type:'Short Film',title:'Nửa Tờ Giấy Gặp Bấy Nhiêu Tay',en:'Through Hands, Through Lives',
       credits:'Director: Hà Tất Thành · Producer: Quốc Hưng',
       awards:['Certificate of Merit — Golden Kite Awards 2025']},
    ],
    sw:[
      {n:'Adobe Premiere Pro, CapCut',d:'Video editing, audio adjustment, effects, workflow organisation'},
      {n:'PluralEyes 4',d:'Fast and accurate video/audio synchronisation'},
      {n:'Canva, Google Slides',d:'Proposal, treatment and moodboard creation'},
      {n:'Google Sheets',d:'Shot lists, budgets, reports, production tracking'},
      {n:'Google Docs',d:'Production notes, contracts and documentation'},
      {n:'Cine Tracer',d:'3D storyboard and shot visualisation'},
      {n:'Adobe Photoshop',d:'Image editing'},
      {n:'After Effects, Illustrator',d:'Basic knowledge, improving skills'},
      {n:'ChatGPT, Gemini',d:'Research, summarisation, reference generation, workflow automation'},
    ],
    exp:[
      'Adaptable and quick to integrate into new environments',
      'Energetic and proactive in demanding tasks',
      'Committed to continuous learning',
      'Strong observation and analytical thinking',
      'Detailed planning and multi-team coordination',
      'Leadership and collaboration in film production',
      'Creative problem solving and innovation',
    ],
  },
  vi:{
    sub:'Nhà làm phim tự do — TP. Hồ Chí Minh', hint:'',
    nsub:'Nhà làm phim tự do — TP. Hồ Chí Minh',
    resFile:'assets/CV_VIE.pdf', resTxt:'Tải CV',
    lblAbout:'Giới thiệu', lblFilms:'Danh mục phim & Giải thưởng',
    lblSw:'Năng lực phần mềm', lblExp:'Kỹ năng chuyên môn',
    about:[
      'Tôi là Nguyễn Vũ Quốc Hưng, nhà làm phim trẻ và freelancer trong các vai trò Đạo diễn, Nhà sản xuất, Trợ lý đạo diễn và Biên tập viên, hiện hoạt động tại TP. Hồ Chí Minh.',
      'Tôi đang trên hành trình khám phá bản thân trong thế giới rộng lớn này, với điện ảnh là con đường tôi chọn để tìm câu trả lời.',
      'Là nhà làm phim mới, tôi chủ động tìm kiếm cơ hội ở mọi vị trí trong đoàn phim, kết hợp kỹ năng và tinh thần học hỏi để cống hiến hết mình.',
    ],
    quote:'"Bạn chỉ nhận lại những gì bạn sẵn sàng bỏ ra." — Hirokazu Kore-eda',
    films:[
      {type:'Phim ngắn',title:'Hạnh Phúc Của Ánh Dương',
       awards:['Phim ngắn hay nhất — 1 Minute To Shine (Đại học FPT)']},
      {type:'Phim tài liệu ngắn',title:'Thêm Một "Dấu Phẩy"',
       awards:['Trình chiếu — Lagi Short Film Night (Trigger Film Academy)',
               'Trình chiếu — Xinê Xem Fest 2024 (Xinê House)',
               'Trình chiếu — Filmmaker Lift-Off Sessions 2026, Vol. 1',
               'Giải Khán giả yêu thích — Filmmaker Lift-Off Sessions 2026, Vol. 1']},
      {type:'Phim ngắn',title:'Lặng Lẽ Trôi Về',
       awards:['Trình chiếu — Filmmaker Lift-Off Sessions 2026, Vol. 1',
               "Giải Bình chọn Hội đồng  — Filmmaker Lift-Off Sessions 2026, Vol. 1",
               'Đề cử — Filmmaker Lift-Off Season Awards 2026']},
      {type:'Phim ngắn',title:'Nửa Tờ Giấy Gặp Bấy Nhiêu Tay',
       credits:'Đạo diễn: Hà Tất Thành · Sản xuất: Quốc Hưng',
       awards:['Bằng khen Giải Cánh Diều 2025']},
    ],
    sw:[
      {n:'Adobe Premiere Pro, CapCut',d:'Dựng video, chỉnh âm thanh và hiệu ứng'},
      {n:'PluralEyes 4',d:'Đồng bộ hình ảnh và âm thanh'},
      {n:'Canva, Google Slides',d:'Proposal, treatment, moodboard'},
      {n:'Google Sheets',d:'Shot list, ngân sách, báo cáo sản xuất'},
      {n:'Google Docs',d:'Ghi chú, hợp đồng, hồ sơ sản xuất'},
      {n:'Cine Tracer',d:'Storyboard 3D'},
      {n:'Adobe Photoshop',d:'Chỉnh sửa ảnh'},
      {n:'After Effects, Illustrator',d:'Kiến thức cơ bản, đang nâng cao'},
      {n:'ChatGPT, Gemini',d:'Nghiên cứu, tóm tắt nội dung, hỗ trợ workflow'},
    ],
    exp:[
      'Linh hoạt và thích nghi nhanh với môi trường mới',
      'Tinh thần chủ động, sẵn sàng đối mặt thử thách',
      'Cam kết học hỏi và phát triển nghề nghiệp',
      'Tư duy phân tích và giải quyết vấn đề tốt',
      'Kinh nghiệm lập kế hoạch và điều phối nhiều bộ phận',
      'Khả năng lãnh đạo và phối hợp đội nhóm',
      'Tư duy sáng tạo và cải tiến',
    ],
  },
};



/* ══ PAGE 3 DATA — PRODUCTION PROJECTS ══════ */
